### ISSUE TITLE
Missing Module: ModelString.js

### ISSUE THREAD

**Issue by nightsyde** [AYLIEN/aylien_newsapi_nodejs#4]
Warnings.js Line 12:
`var _ModelString = _interopRequireDefault(require("./ModelString"));`

File is not found, and server will not start without the required file.

`Error: Cannot find module './ModelString'
Require stack:
- <path>\node_modules\aylien-news-api\dist\model\Warning.js
- <path>\node_modules\aylien-news-api\dist\model\Stories.js
- <path>\node_modules\aylien-news-api\dist\index.js
- <path>\src\server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (<path>\node_modules\aylien-news-api\dist\model\Warning.js:12:43)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<path>\\node_modules\\aylien-news-api\\dist\\model\\Warning.js',
    '<path>\\node_modules\\aylien-news-api\\dist\\model\\Stories.js',
    '<path>\\node_modules\\aylien-news-api\\dist\\index.js',
    '<path>\\src\\server\\index.js'
  ]
}`

**Comment by mdibaiee** [comment]
Hi, thank you for reporting this issue. We just released a new patch version `4.1.1` which fixes this issue, please try this patch and let us know how it goes.

**Comment by mdibaiee** [comment]
I will close this issue, if you still face issues please reply here and we can re-open.
